---
title: Ellington K-8 School
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    image: 
permalink: pretty
exclude:
- README.md
logo: "/uploads/ellington.png"
